name: agence

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  agence:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /agence') ||
      startsWith(github.event.comment.body, '/agence')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Run agence
        uses: ./github
        env:
          AGENCE_API_KEY: ${{ secrets.AGENCE_API_KEY }}
          AGENCE_PERMISSION: '{"bash": "deny"}'
        with:
          model: opencode/claude-opus-4-5
